version: '3.3'

services: 
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports: 
      - ${DB_PORT}:${DB_PORT}'
    volumes: 
      - requesterr:/var/lib/mysql
    env_file: ./.env
  cache:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file: ./.env

volumes: 
  requesterr: